export const dataItems = [
    {
        "key": 1,
        "Dessert": "Cupcake",
        "Calories": 356,
        "Fat": 16,
        "Sugar": 40,
        "Protein": 4,
        "Carbohydrates": 50,
        "Ingredients": "Flour, Sugar, Eggs, Butter, Milk",
        "Description": "A small cake designed to serve one person, topped with frosting.",
        "ImageURL": "https://example.com/cupcake.jpg",
        "checked": false
    },
    {
        "key": 2,
        "Dessert": "Eclair",
        "Calories": 262,
        "Fat": 16,
        "Sugar": 24,
        "Protein": 5,
        "Carbohydrates": 28,
        "Ingredients": "Flour, Sugar, Butter, Eggs, Chocolate",
        "Description": "A long pastry filled with cream and topped with chocolate icing.",
        "ImageURL": "https://example.com/eclair.jpg",
        "checked": false
    },
    {
        "key": 3,
        "Dessert": "Frozen yogurt",
        "Calories": 159,
        "Fat": 6,
        "Sugar": 17,
        "Protein": 3,
        "Carbohydrates": 24,
        "Ingredients": "Yogurt, Sugar, Milk",
        "Description": "A frozen dessert made from yogurt and milk.",
        "ImageURL": "https://example.com/frozen_yogurt.jpg",
        "checked": false
    },
    {
        "key": 4,
        "Dessert": "Gingerbread",
        "Calories": 305,
        "Fat": 3.7,
        "Sugar": 30,
        "Protein": 2,
        "Carbohydrates": 60,
        "Ingredients": "Flour, Sugar, Ginger, Butter, Molasses",
        "Description": "A sweet, spiced cake flavored with ginger.",
        "ImageURL": "https://example.com/gingerbread.jpg",
        "checked": false
    },
    {
        "key": 5,
        "Dessert": "Ice cream sandwich",
        "Calories": 237,
        "Fat": 9,
        "Sugar": 18,
        "Protein": 3,
        "Carbohydrates": 35,
        "Ingredients": "Ice cream, Cookies",
        "Description": "A dessert consisting of ice cream between two biscuits or cookies.",
        "ImageURL": "https://example.com/ice_cream_sandwich.jpg",
        "checked": false
    },
    {
        "key": 6,
        "Dessert": "Jelly Bean",
        "Calories": 375,
        "Fat": 0,
        "Sugar": 75,
        "Protein": 0,
        "Carbohydrates": 94,
        "Ingredients": "Sugar, Corn syrup, Flavorings",
        "Description": "Small, bean-shaped sugar candies with soft shells and gel interiors.",
        "ImageURL": "https://example.com/jelly_bean.jpg",
        "checked": false
    },
    {
        "key": 7,
        "Dessert": "Lemon Bar",
        "Calories": 280,
        "Fat": 12,
        "Sugar": 36,
        "Protein": 3,
        "Carbohydrates": 38,
        "Ingredients": "Flour, Sugar, Lemon juice, Butter, Eggs",
        "Description": "A tart and sweet bar cookie with a lemon-flavored filling on top of a buttery crust.",
        "ImageURL": "https://example.com/lemon_bar.jpg",
        "checked": false
    },
    {
        "key": 8,
        "Dessert": "Brownie",
        "Calories": 243,
        "Fat": 10,
        "Sugar": 27,
        "Protein": 3,
        "Carbohydrates": 36,
        "Ingredients": "Flour, Sugar, Cocoa powder, Eggs, Butter",
        "Description": "A rich, chocolate dessert with a moist, dense texture.",
        "ImageURL": "https://example.com/brownie.jpg",
        "checked": false
    },
    {
        "key": 9,
        "Dessert": "Apple Pie",
        "Calories": 295,
        "Fat": 14,
        "Sugar": 19,
        "Protein": 2,
        "Carbohydrates": 41,
        "Ingredients": "Apples, Sugar, Flour, Butter, Cinnamon",
        "Description": "A classic dessert consisting of a crust filled with sliced apples, sugar, and cinnamon.",
        "ImageURL": "https://example.com/apple_pie.jpg",
        "checked": false
    },
    {
        "key": 10,
        "Dessert": "Cheesecake",
        "Calories": 321,
        "Fat": 23,
        "Sugar": 21,
        "Protein": 6,
        "Carbohydrates": 26,
        "Ingredients": "Cream cheese, Sugar, Eggs, Graham crackers, Butter",
        "Description": "A creamy dessert with a smooth texture, often topped with fruit or chocolate.",
        "ImageURL": "https://example.com/cheesecake.jpg",
        "checked": false
    },
    {
        "key": 11,
        "Dessert": "Pudding",
        "Calories": 151,
        "Fat": 4,
        "Sugar": 22,
        "Protein": 3,
        "Carbohydrates": 25,
        "Ingredients": "Milk, Sugar, Cornstarch, Vanilla extract",
        "Description": "A sweet, creamy dessert typically made from milk or cream and thickened with cornstarch.",
        "ImageURL": "https://example.com/pudding.jpg",
        "checked": false
    },
    {
        "key": 12,
        "Dessert": "Donut",
        "Calories": 195,
        "Fat": 11,
        "Sugar": 10,
        "Protein": 3,
        "Carbohydrates": 22,
        "Ingredients": "Flour, Sugar, Milk, Eggs, Yeast",
        "Description": "A sweet, deep-fried dough, often glazed or topped with sugar.",
        "ImageURL": "https://example.com/donut.jpg",
        "checked": false
    },
    {
        "key": 13,
        "Dessert": "Carrot Cake",
        "Calories": 326,
        "Fat": 17,
        "Sugar": 31,
        "Protein": 4,
        "Carbohydrates": 45,
        "Ingredients": "Carrots, Flour, Sugar, Eggs, Cream cheese",
        "Description": "A moist cake made with grated carrots, often topped with cream cheese frosting.",
        "ImageURL": "https://example.com/carrot_cake.jpg",
        "checked": false
    },
    {
        "key": 14,
        "Dessert": "Banana Split",
        "Calories": 430,
        "Fat": 14,
        "Sugar": 60,
        "Protein": 6,
        "Carbohydrates": 68,
        "Ingredients": "Bananas, Ice cream, Chocolate syrup, Whipped cream, Nuts",
        "Description": "A dessert consisting of a banana cut in half and topped with ice cream, chocolate syrup, and whipped cream.",
        "ImageURL": "https://example.com/banana_split.jpg",
        "checked": false
    },
    {
        "key": 15,
        "Dessert": "Macaron",
        "Calories": 70,
        "Fat": 3,
        "Sugar": 8,
        "Protein": 2,
        "Carbohydrates": 10,
        "Ingredients": "Almond flour, Sugar, Egg whites, Food coloring",
        "Description": "A sweet meringue-based confection made with egg whites, icing sugar, granulated sugar, almond meal, and food coloring.",
        "ImageURL": "https://example.com/macaron.jpg",
        "checked": false
    },
    {
        "key": 16,
        "Dessert": "Tiramisu",
        "Calories": 240,
        "Fat": 15,
        "Sugar": 16,
        "Protein": 5,
        "Carbohydrates": 20,
        "Ingredients": "Mascarpone cheese, Coffee, Ladyfingers, Cocoa powder, Sugar",
        "Description": "An Italian dessert consisting of layers of coffee-soaked ladyfingers and a whipped mixture of eggs, sugar, and mascarpone cheese.",
        "ImageURL": "https://example.com/tiramisu.jpg",
        "checked": false
    },
    {
        "key": 17,
        "Dessert": "Baklava",
        "Calories": 290,
        "Fat": 18,
        "Sugar": 19,
        "Protein": 5,
        "Carbohydrates": 31,
        "Ingredients": "Phyllo dough, Honey, Nuts, Butter, Sugar",
        "Description": "A layered pastry dessert made of filo pastry, filled with chopped nuts, and sweetened with syrup or honey.",
        "ImageURL": "https://example.com/baklava.jpg",
        "checked": false
    }];
